- admin/index.php
- assets/css/style.css
> [FE] Admin Dashboard

- admin/editProfileDriver.php
> [FE] Admin Side Edit Profile Driver #27

- admin/editProfilePassenger.php
> [FE] Edit Profile Page for Passenger #27

- admin/driverView.php
> [FE] Driver Display Page with it's Detail #26

- admin/addDrivers.php
> [FE] A new page for adding a New Driver User #49

- signUp.php
> [FE] Sign Up Page #10

- assets/css/style.css
- assets/js/homePage/details.js
- assets/js/homePage/map.js
- passenger/homePage.php
> #2 Fixed the full screen of map, #62 Added driver info card, #65 Implement Custom Marker

- assets/images/remove-member.svg
- passenger/accountView.php
- passenger/removeCircleMember.php
> [FE] Remove Circle Member page and modal #44

- driver/changeAdminStatusDriver.php
- passenger/changeAdminStatusPassenger.php
- passenger/scanQr.php
The implemented feature is the same for Passenger and Driver
Note: wala pa me nung navbar for driver na bagong gawa pero the directory is the same nung main
> #43 Implemented a Change Admin Status for Passenger and Driver

- assets/css/style.css
- assets/shared/navbarAdmin.php
- assets/shared/navbarDriver.php
- assets/shared/navbarPassenger.php
> Changes on the height of the Navbar #22

- index.php
- signUp.php
files changed
index.php
signUp.php
> #91 Login and SignUp Integration

- assets/data/EmergencyHotline.json
- passenger/emergencyContact.php
Files changed
passenger/emergencyContact.php
assets/data/EmergencyHotline.json
> [BE] Integrate Emergency Contact Access for Users (Phone Visibility in Circles #92

- passenger/createCircle.php
- passenger/emergencyContact.php
- passenger/joinCircle.php
Files changed:
passenger/createCircle.php
passenger/joinCircle.php
passenger/emergencyContact.php
> Minor revision on Ticket #102, #103

- driver/profileInformation.php
- passenger/changeAdminStatusPassenger.php
- passenger/circle.php
- passenger/circleDetails.php
- passenger/editCircleName.php
- passenger/getDriver.php
- passenger/leaveCircleAction.php
- passenger/removeCircleMember.php
- passenger/scanQr.php
- passenger/verificationScreen.php
Added a modal to all of the circle management and all of the scanqr error handlers.
The qr for driver in profileInformation.php is now downloadable
And added a placeholder for qr in qr scanner
> #94 Debugged the Circle Management, and added a feature in qr scanner and profile info for drivers

- assets/shared/header.php
- driver/circle.php
- driver/circleDetails.php
- driver/editCircleName.php
- driver/inviteMember.php
- driver/leaveCircleAction.php
- driver/removeCircleMember.php
- driver/settings.php
> #119 Added the Circle Management in Driver Side

- assets/php/storeLocation.php
- driver/groupPage.php
- driver/index.php
- passenger/index.php
**Modified Files:**
- `assets/php/storeLocation.php`: Updated location handling logic.
- `driver/index.php`: Refined driver index with number of Passengers.
- `passenger/groupPage.php`: Adjusted group page behavior.
- `passenger/index.php` Adjusted index page behavior.
**New File:**
- `driver/groupPage.php`: Added a new group page view for drivers.
These changes enhance page separation between driver and passenger roles and improve location handling functionality.
> [BE] Added driver side index and groupPage #123, #125

- admin/deleteDriver.php
- admin/deletePassenger.php
- admin/driverView.php
- admin/drivers.php
- admin/index.php
- admin/passengers.php
- admin/passengersView.php
added filter sort, and recover features for all in admin side
inactive - general term for deleted/suspended/banned accounts
> Added features on #97 drivers and passengers management

- driver/changeAdminStatusDriver.php
- driver/circleDetails.php
- passenger/changeAdminStatusPassenger.php
- passenger/circleDetails.php
> remove the circle details if member in passenger and driver

- index.php
- signUp.php
IF USER INPUTS MORE THAN 15 CHARACTERS
IF USER DOESN'T INPUTED VALID CONTACT NUMBER
> ENHANCED | SIGNUP INPUT VALIDATION

- admin/addDrivers.php
Summary of Changes **admin/addDrivers.php**
- Added server-side validation for required fields (first name, last name, email, password, contact number, model, plate number, address, TODA registration, and driver photo).
- Implemented Bootstrap modals for feedback:
- ✅ Success modal shows when registration is completed.
- ⚠️ Error modal shows with descriptive messages when fields or the photo are missing.
- Handled file input (photo) validation in PHP instead of using required to avoid the “invalid form control not focusable” issue.
- Preserved user input values in form fields when an error occurs (so users don’t need to re-enter all data).
- Reset form fields including photo input after successful registration and closing of the success modal.
- Added inline JavaScript for number-only …
> IMPROVED | Insert Validation

- driver/emergencyContact.php
- passenger/emergencyContact.php
Emergency contacts are now displayed only once per person, even if they belong to multiple circles.
> fixed bugs

- assets/data/EmergencyHotline.json
> UPDATED | EMERGENCY HOTLINE

- driver/profileInformation.php
added a name in the qr download for the corresponding driver
> added a name in qr download

- admin/settings.php
- driver/settings.php
- passenger/settings.php
> Survey Form Button
